# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d121a2d8be24d899b52503a98e0fba19341af6eeb7f5c4e24c62f0fa8f63b33d6354871a355445c6db84ba7d99782b9da306dacc5006a2b53dfc4578f8f25915

test:
  secret_key_base: 44aa4315455d902068c47201815dd0eb2f6fafa178bd82ebecf5a716c1fc5b5ea0e5d2166431c5f3c4239092370e6ab7b35603aff47123c131f61f7838f884d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
